const matcher = require('./matcher');

let wordyWords = [
  'a number of',
  'abundance',
  'accede to',
  'accelerate',
  'accentuate',
  'accompany',
  'accomplish',
  'accorded',
  'accrue',
  'acquiesce',
  'acquire',
  'additional',
  'adjacent to',
  'adjustment',
  'admissible',
  'advantageous',
  'adversely impact',
  'advise',
  'aforementioned',
  'aggregate',
  'aircraft',
  'all of',
  'all things considered',
  'alleviate',
  'allocate',
  'along the lines of',
  'already existing',
  'alternatively',
  'amazing',
  'ameliorate',
  'anticipate',
  'apparent',
  'appreciable',
  'as a matter of fact',
  'as a means of',
  'as far as I\'m concerned',
  'as of yet',
  'as per',
  'as to',
  'as yet',
  'ascertain',
  'assistance',
  'at the present time',
  'at this time',
  'attain',
  'attributable to',
  'authorize',
  'because of the fact that',
  'belated',
  'benefit from',
  'bestow',
  'by means of',
  'by virtue of the fact that',
  'by virtue of',
  'cease',
  'close proximity',
  'commence',
  'comply with',
  'concerning',
  'consequently',
  'consolidate',
  'constitutes',
  'demonstrate',
  'depart',
  'designate',
  'discontinue',
  'do damage to',
  'do harm to',
  'due to the fact that',
  'during the course of',
  'each and every',
  'economical',
  'eliminate',
  'elucidate',
  'employ',
  'endeavor',
  'enumerate',
  'equitable',
  'equivalent',
  'evaluate',
  'evidenced',
  'exclusively',
  'expedite',
  'expend',
  'expiration',
  'facilitate',
  'factual evidence',
  'feasible',
  'finalize',
  'first and foremost',
  'for all intents and purposes',
  'for the duration of',
  'for the most part',
  'for the purpose of',
  'forfeit',
  'formulate',
  'have a tendency to',
  'honest truth',
  'however',
  'if and when',
  'impacted',
  'implement',
  'in a manner of speaking',
  'in a timely manner',
  'in a very real sense',
  'in accordance with',
  'in addition',
  'in all likelihood',
  'in an effort to',
  'in between',
  'in excess of',
  'in lieu of',
  'in light of the fact that',
  'in many cases',
  'in my opinion',
  'in need of',
  'in order to',
  'in regard to',
  'in some instances',
  'in terms of',
  'in the affirmative',
  'in the case of',
  'in the course of',
  'in the event that',
  'in the final analysis',
  'in the midst of',
  'in the nature of',
  'in the near future',
  'in the negative',
  'in the process of',
  'inception',
  'incumbent upon',
  'indicate',
  'indication',
  'initiate',
  'irregardless',
  'is applicable to',
  'is authorized to',
  'is responsible for',
  'it is essential',
  'it is',
  'it seems that',
  'it was',
  'magnitude',
  'majority of',
  'make an effort',
  'maximum',
  'methodology',
  'minimize',
  'minimum',
  'modify',
  'monitor',
  'multiple',
  'myriad of',
  'necessitate',
  'nevertheless',
  'not certain',
  'not many',
  'not often',
  'not unless',
  'not unlike',
  'notwithstanding',
  'null and void',
  'numerous',
  'objective',
  'obligate',
  'obtain',
  'of late',
  'of the fact that',
  'off of',
  'on the contrary',
  'on the other hand',
  'one particular',
  'optimum',
  'outside of',
  'overall',
  'owing to the fact that',
  'participate',
  'particulars',
  'pass away',
  'pertaining to',
  'point in time',
  'portion',
  'possess',
  'preclude',
  'previous to',
  'previously',
  'prior to',
  'prioritize',
  'procure',
  'proficiency',
  'provided that',
  'purchase',
  'put simply',
  'readily apparent',
  'refer back',
  'regarding',
  'relocate',
  'remainder',
  'remuneration',
  'requirement',
  'reside',
  'residence',
  'retain',
  'satisfy',
  'shall',
  'should you wish',
  'similar to',
  'solicit',
  'sooner rather than later',
  'span across',
  'strategize',
  'subsequent',
  'substantial',
  'successfully complete',
  'sufficient',
  'terminate',
  'that which',
  'the month of',
  'the point I am trying to make',
  'therefore',
  'time period',
  'took advantage of',
  'transmit',
  'transpire',
  'type of',
  'until such time as',
  'utilization',
  'utilize',
  'validate',
  'various different',
  'what I mean to say is',
  'whether or not',
  'with respect to',
  'with the exception of',
  'witnessed',
   'according to',
  'across the board',
  'add insult to injury',
  'all in all',
  'as a result of',
  'as far as',
  'as if',
  'as is often the case',
  'as opposed to',
  'as such',
  'as yet',
  'at the end of the day',
  'at the present moment',
  'back to square one',
  'be all and end all',
  'bear in mind',
  'believe it or not',
  'best of both worlds',
  'bite the bullet',
  'break the ice',
  'buckle down',
  'burn the midnight oil',
  'burst your bubble',
  'call it a day',
  'catch someone\'s eye',
  'checkmate',
  'chew the fat',
  'chomp at the bit',
  'clear as mud',
  'close but no cigar',
  'come hell or high water',
  'crack of dawn',
  'cry over spilled milk',
  'cut to the chase',
  'dead as a doornail',
  'devil\'s advocate',
  'diamond in the rough',
  'do a double-take',
  'down and out',
  'draw the line',
  'drum up business',
  'duck and cover',
  'dumb as a doornail',
  'dutch courage',
  'easy as pie',
  'eat crow',
  'elephant in the room',
  'even the playing field',
  'every cloud has a silver lining',
  'everything but the kitchen sink',
  'eye for an eye',
  'face the music',
  'fall off the wagon',
  'feather in one\'s cap',
  'feather your nest',
  'fifteen minutes of fame',
  'filthy rich',
  'fit as a fiddle',
  'flash in the pan',
  'flesh and blood',
  'flog a dead horse',
  'fly by the seat of one\'s pants',
  'for the birds',
  'force to be reckoned with',
  'forgive and forget',
  'freak of nature',
  'get a leg up',
  'get down to brass tacks',
  'get the ball rolling',
  'get your ducks in a row',
  'give the benefit of the doubt',
  'go down in flames',
  'go for broke',
  'go the extra mile',
  'go up in smoke',
  'green thumb',
  'grin and bear it',
  'grind to a halt',
  'gut feeling',
  'hair of the dog',
  'haste makes waste',
  'have a blast',
  'have a cow',
  'have a dog in this fight',
  'have a field day',
  'have a fit',
  'have a screw loose',
  'have eyes in the back of your head',
  'have the last laugh',
  'hear it on the grapevine',
  'hit the hay',
  'hit the nail on the head',
  'hit the sack',
  'hold your horses',
  'hot under the collar',
  'if the shoe fits, wear it',
  'in a heartbeat',
  'in a jiffy',
  'in a pickle',
  'in a nutshell',
  'in a row',
  'in the doghouse',
  'in the same boat',
  'in the thick of it',
  'it takes two to tango',
  'jump on the bandwagon',
  'jump through hoops',
  'jump the gun',
  'jump to conclusions',
  'keep it under wraps',
  'keep your chin up',
  'kick the bucket',
  'kick the can down the road',
  'kill two birds with one stone',
  'kiss and tell',
  'kiss of death',
  'knock on wood',
  'know the ropes',
  'knuckle down',
  'last straw',
  'let the cat out of the bag',
  'lick your wounds',
  'like a bat out of hell',
  'like a moth to a flame',
  'like it or lump it',
  'lion\'s share',
  'live and learn',
  'long in the tooth',
  'look before you leap',
  'lose your head',
  'lose your touch',
  'make a long story short',
  'make no bones about it',
  'make waves',
  'method to my madness',
  'miss the boat',
  'monkey see, monkey do',
  'more power to you',
  'my cup of tea',
  'needle in a haystack',
  'nip it in the bud',
  'no pain, no gain',
  'nothing to sneeze at',
  'odds and ends',
  'off the top of my head',
  'old hat',
  'on cloud nine',
  'on pins and needles',
  'out of left field',
  'out of the frying pan and into the fire',
  'over a barrel',
  'paint the town red',
  'pass the buck',
  'pay through the nose',
  'pegged it',
  'people who live in glass houses shouldn\'t throw stones',
  'piece of cake',
  'pig in a poke',
  'pound the pavement',
  'pull a fast one',
  'pull out all the stops',
  'pull someone\'s leg',
  'pull strings',
  'pull the wool over someone\'s eyes',
  'pull yourself together',
  'put all your eggs,
];

// Replace a basic white-space with more-robust white-space matching for new lines, half-space etc.
wordyWords = wordyWords.map((w) => w.replace(/ /g, '[\\b\\s\\u200C]*'));
const wordyRegex = new RegExp(`\\b(?<!-)(${wordyWords.join('|')})\\b`, 'gi');

module.exports = function isTextWordy(text) {
  return matcher(wordyRegex, text);
};
